[package]
name = "computer_v1"
version = "0.1.0"
authors = ["Synlo <synlo@outlook.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
regex = "1"
colored = "1.9.3"